# **5.16 *List* 2 Dimensi**

In [ ]:
#Misal kita buat list matrik

matrik = [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
]
print(matrik)

#Dengan perintah print akan mencetak list matrik yang kita buat

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]


In [ ]:
matrik [0]

#Indeks 0 merupakan indeks pertama pada list, maka outputnya adalah [1,2,3,4]

[1, 2, 3, 4]

In [ ]:
matrik [2][0]

#Perintah ini untuk menghasilkan output nilai pada baris ke-2 dan pada kolom ke-0

9

In [ ]:
matrik [2][0]=50
print(matrik[2][0])

#Perintah ini akan mengganti nilai yang asli dengan nilai yang baru kita tentukan

50


In [ ]:
matrik

#Dengan perintah ini saja akan menghasilkan output seluruh list matrik
#Dengan catatan akan ada nilai yang berubah karena sudah kita ganti

[[1, 2, 3, 4], [5, 6, 7, 8], [50, 10, 11, 12], [13, 14, 15, 16]]

In [ ]:
matrik = [
    [5,9,6,8,12],
    [3,7,4,10,2],
    [7,5,15,2,8],
    [11,4,9,5,3],
    [5,9,8,16,2]
]
print(matrik)

[[5, 9, 6, 8, 12], [3, 7, 4, 10, 2], [7, 5, 15, 2, 8], [11, 4, 9, 5, 3], [5, 9, 8, 16, 2]]


In [ ]:
for baris in matrik:
  print(baris)
  for kolom in baris:
    print(kolom)

[5, 9, 6, 8, 12]
5
9
6
8
12
[3, 7, 4, 10, 2]
3
7
4
10
2
[7, 5, 15, 2, 8]
7
5
15
2
8
[11, 4, 9, 5, 3]
11
4
9
5
3
[5, 9, 8, 16, 2]
5
9
8
16
2


# **5.17 *Tuples*** 

In [ ]:
#Tuple adalah tipe data pada Python yang tidak dapat diubah

#Disini saya membuat daftar beberapa huruf

huruf = ('a','b','c','d','e','f')
print(huruf[2])

#Output dari perintah ini adalah indeks dari 2, yaitu c

c


In [ ]:
for isi in huruf:
  print(isi)

#Perintah ini masih simple, yaitu mengubah perintah huruf menjadi isi

a
b
c
d
e
f


In [ ]:
print(huruf[0:3])

#Sesuai dengan perintah yaitu output yang akan muncul adalah urutan dari 
#indeks ke-0 adalah a sampai indeks ke-3 yaitu d
#Tetapi pada python indeks yang kita inginkan akan berkurang satu

('a', 'b', 'c')


In [ ]:
print(huruf[0:4])
print(' ')
for isi in huruf[0:4]:
  print(isi)

('a', 'b', 'c', 'd')
 
a
b
c
d


In [ ]:
huruf[0]=10

#Sesuai dengan definisi tuples yaitu data tidak dapat dirubah
#Maka dari itu terjadi error ketika ingin merubah data

TypeError: ignored

In [ ]:
huruf.append('h')

#Data tidak dapat dirubah jika menggunakan perintah tuples
#Jika ingin merubah data sebaiknya menggunakan list agar tidak error

AttributeError: ignored

In [ ]:
huruf.remove('a')

#Data tidak dapat dirubah jika menggunakan perintah tuples

AttributeError: ignored

In [ ]:
huruf.count('f')

#Arti dari perintah ini adalah menghitung banyaknya huruf f pada data yang kita buat

1

In [ ]:
huruf.index('d')
#Arti dari perintah ini adalah menentukan huruf yang kita inginkan berada pada indeks ke berapa

3

# **5.18 *Dictionaries***

In [ ]:
data_orang = {
    "nama" : "Doni Lukman",
    "umur" : 19,
    "apakah_single" : False
}
print(data_orang["nama"])
print(data_orang.get("nama"))
print(data_orang.get("tanggal lahir"))

Doni Lukman
Doni Lukman
None


In [ ]:
data_orang["HP"] = "081447896269"
print(data_orang["HP"])
print(data_orang.get("HP"))

081447896269
081447896269


# **5.19 Fungsi dalam Python**

In [ ]:
#Fungsi pada python ini dapat digunakan untuk menjalankan perintah
#Kita harus membuat definisinya terlebih dahulu agar perintah dapat dijalankan

def full_name(first_name,last_name):
  print(f"Nama lengkapnya adalah {first_name} {last_name}")

In [ ]:
first_name = input("Nama depan anda adalah ")
last_name = input("Nama belakang anda adalah ")
full_name(first_name,last_name)

#Pada cell sebelumnya saya sudah membuat definisi dari perintah yang diinginkan
#Jadi pada fungsi ini kita dapat menginput data sesuai perintah pada saat kode dijalankan

Nama depan anda adalah Kleo
Nama belakang anda adalah Handayani
Nama lengkapnya adalah Kleo Handayani


In [1]:
#Fungsi parameter opsional

def suhu_udara (daerah, derajat, satuan = "celcius"):
  print(f"Suhu di {daerah} adalah {derajat} derajat {satuan}")

#Pada fungsi yang saya buat saya mendefinisikan tiga parameter
#Dua parameter pertama adalah bersifat wajib sedangkan parameter ketiga tidak wajib
#Jika tidak kita isi, maka nilai default-nya adalah “celcius”

In [2]:
suhu_udara("Kuta Selatan", 29)
suhu_udara("Gianyar", 86, "Farenheit")

#Saya mencoba dua cara, yaitu menambahkan parameter ketiga dan tidak ditambahkan
#Maka outputnya pun akan berbeda

Suhu di Kuta Selatan adalah 29 derajat celcius
Suhu di Gianyar adalah 86 derajat Farenheit


In [ ]:
#Fungsi pada cell ini akan mengembalikan nilai

def luas_persegi(sisi):
  return sisi*sisi

#Perintah return digunakan untuk mengembalikan nilai

print("Luas persegi dengan sisi 7 adalah:", luas_persegi(7))
persegi_besar = luas_persegi(10)
persegi_kecil = luas_persegi(2)
print("Total luas persegi besar dan kecil adalah:", persegi_besar + persegi_kecil)

#Nilai yang dikembalikan suatu fungsi, bisa kita olah kembali untuk berbagai kebutuhan.

Luas persegi dengan sisi 7 adalah: 49
Total luas persegi besar dan kecil adalah: 104


# **5.20 Numpy**

In [2]:
#Numpy memiliki fungsi yang memudahkan kita untuk melakukan perhitungan saintifik
#List juga dapat melakukan perhitungan saintifik, namun beberapa operasi perhitungan harus dibuat secara manual

import numpy as np

#Numpy harus kita impor dulu agar bisa digunakan di dalam program.

# **5.20.1 Perintah Dasar pada *Numpy***

In [6]:
#Pada kode ini akan menghitung hasil penjumlahan tiap elemen di list

import numpy as np
matrik_a = np.array([
    [11, 12, 13],
    [14, 15, 16],
    [17, 18, 19]])
matrik_b = np.array([
    [13, 12, 11],
    [16, 15, 14],
    [19, 18, 17]])
hasil = matrik_a + matrik_b
print(hasil)

#Matriks di dalam kode program biasanya dibuat dengan array karena matrik terdiri dari baris dan kolom.
#Karena pada cell ini saya akan menghitung hasil penjumlahan tiap elemen,
#maka saya menggunakan operasi penjumlahan

[[24 24 24]
 [30 30 30]
 [36 36 36]]


In [8]:
import numpy as np
matrik_a = np.array([
    [1, 2],
    [3, 4]])
matrik_b = np.array([
    [5, 6],
    [7, 8]])
hasil = matrik_b - matrik_a
print(hasil)

#Karena pada cell ini saya akan menghitung hasil pengurangan tiap elemen,
#maka saya menggunakan operasi pengurangan

[[4 4]
 [4 4]]


# **5.20.2 Memanggil Anggota, Kolom dan Baris dengan *Numpy***

In [9]:
import numpy as np
d = np.array([[5,9,6,8,12], [3,7,4,10,2], [7,5,15,2,8], [11,4,9,5,3], [5,9,8,16,2]])
print(d)

[[ 5  9  6  8 12]
 [ 3  7  4 10  2]
 [ 7  5 15  2  8]
 [11  4  9  5  3]
 [ 5  9  8 16  2]]


In [12]:
d[1,4]

2

In [14]:
d[2,:]

array([ 7,  5, 15,  2,  8])

# **5.20.3 Matrix pada *Numpy***

In [33]:
#Pada kode ini saya membuat matriks dengan perintah untuk mengubah ukurannya

matrik_a = np.array([1, 1, 1, 1, 1, 1, 1, 1, 1])

print("Matrik awal: ")
print(matrik_a)
print("Ukuran = ", matrik_a.shape)

hasil = matrik_a.reshape(3, 3)

print("Mengubah ke 3x3: ")
print(hasil)

#Perintah .shape berfungsi untuk mengetahui ukuran array
#perintah .reshape digunakan untuk mengubah ukuran array

Matrik awal: 
[1 1 1 1 1 1 1 1 1]
Ukuran =  (9,)
Mengubah ke 3x3: 
[[1 1 1]
 [1 1 1]
 [1 1 1]]


# **5.20.4 Copy pada *Numpy***

In [19]:
import numpy as np

#Copy memiliki data dan perubahan apapun yang dilakukan copy tidak akan memengaruhi array asli

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(x)
print(arr)

#Disini saya membuat copy array dengan mengubah array asli dan menampilkan kedua array

[1 2 3 4 5]
[42  2  3  4  5]


In [20]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

#Disini saya mencetak nilai untuk memeriksa apakah sebuah array memiliki datanya atau tidak
#Setiap array Numpy memiliki nilai yang mengembalikan None jika array memiliki datanya
#Jika tidak, nilai mengacu pada objek asli

None
[1 2 3 4 5]


# **5.20.5 Operasi Matematika pada *Numpy***

In [4]:
#Numpy memiliki kelebihan untuk memproses operasi matematika

import numpy as np
a = np.array([-1.77, 1.33, -0.22, 0.55, 10])
print (np.around(a, decimals = 1))
#Numpy.around() – digunakan untuk membulatkan beberapa desimal dibelakang koma
#Dengan aturan nilai batas adalah 5

print (np.floor(a))
#Digunakan saat ingin melakukan pembulatan ke bawah

print (np.ceil(a))
#Dilakukan saat ingin melakukan pembulatan ke atas

[-1.8  1.3 -0.2  0.6 10. ]
[-2.  1. -1.  0. 10.]
[-1.  2. -0.  1. 10.]


# **5.20.6 Perkalian Matrik pada *Numpy***

In [23]:
matriks_a = np.array([[1,2],
                     [2,1]])
matriks_b = np.array([[2,2],
                     [1,1]])   

perkalian_biasa = matriks_a*matriks_b
perkalian_matriks = np.dot(matriks_a, matriks_b)
print("Perkalian Biasa Matriks : ")
print(perkalian_biasa)

print("Perkalian Matriks : ")
print(perkalian_matriks)

#Saya membuat 2 variabel yang berisi array 
#Untuk mengalikan matriks tinggal menggunakan fungsi numpy yaitu np.dot(matriks1,matriks2) 
#Jika perkalian biasa tinggal gunakan operasi perkalian biasa

Perkalian Biasa Matriks : 
[[2 4]
 [2 1]]
Perkalian Matriks : 
[[4 4]
 [5 5]]


# **5.20.7 *min*, *max* dan *sum* pada *Numpy***

In [34]:
nilai_siswa = np.array([55, 43, 98, 76 ,65 ,77 ,65, 90])
print("Nilai minimal = ", nilai_siswa.min())
print("Nilai maksimal = ", nilai_siswa.max())
print("Nilai rata-rata = ", nilai_siswa.mean())
print("Total nilai = ", nilai_siswa.sum())

Nilai minimal =  43
Nilai maksimal =  98
Nilai rata-rata =  71.125
Total nilai =  569
